package com.example.meter.model

/**
 * Multi-language String Provider for Light Meter UI (10 Supported Languages)
 */
object AppStrings {

    fun get(lang: AppLanguage): Strings = when (lang) {
        AppLanguage.ENGLISH -> StringsEn
        AppLanguage.SIMPLIFIED_CHINESE -> StringsZh
        AppLanguage.TRADITIONAL_CHINESE -> StringsZhTw
        AppLanguage.JAPANESE -> StringsJa
        AppLanguage.KOREAN -> StringsKo
        AppLanguage.FRENCH -> StringsFr
        AppLanguage.SPANISH -> StringsEs
        AppLanguage.GERMAN -> StringsDe
        AppLanguage.RUSSIAN -> StringsRu
        AppLanguage.ARABIC -> StringsAr
    }

    interface Strings {
        val appTitle: String
        val filmSelect: String
        val spotMeter: String
        val matrixMeter: String
        val multiSpot: String
        val lockHold: String
        val unlockReading: String
        val readingLocked: String
        val liveMetering: String
        val zoneSystem: String
        val rangefinder: String
        val torch: String
        val falseColor: String
        val compensation: String
        val ndFilter: String
        val logShot: String
        val shotLogs: String
        val reciprocityTimer: String
        val framelines: String
        val settings: String
        val menu: String
        val calibrationOffset: String
        val calibrationDesc: String
        val reset: String
        val language: String
        val cameraOptics: String
        val lensSwitch: String
        val ultraWide: String
        val mainWide: String
        val telephoto2x: String
        val telephoto3x: String
        val telephoto5x: String
        val landscapeEquiv: String
        val portraitEquiv: String
        val measuredDistance: String
        val distanceMeasuring: String
        val infinityHyperfocal: String
        val macroRange: String
        val tapToMeasure: String
        val priorityAv: String
        val priorityTv: String
        val priorityIso: String
        val priorityEvLock: String
        val reciprocityComp: String
        val timerStart: String
        val timerPause: String
        val timerReset: String
        val timerCompleted: String
        val formatGate: String
        val gridGuides: String
        val colorFilters: String
        val digitalCropZoom: String
        val clearAll: String
        val notePlaceholder: String
        val saveLog: String
        val delete: String
        val exposureValue: String
        val middleGray: String

        // Comprehensive UI Labels
        val cameraPermissionRequired: String
        val cameraPermissionDesc: String
        val grantPermission: String
        val pinSpot: String
        val apertureLabel: String
        val shutterLabel: String
        val isoLabel: String
        val reciprocityBannerTitle: String
        val reciprocityBannerFormat: String
        val openTimer: String
        val distanceOn: String
        val distanceOff: String
        val menuCalibration: String
        val outOfFovWarning: String
        val switchToUltraWide: String
        val framelineModeMask: String
        val framelineModeZoom: String
        val zoneSystemTitle: String
        val alignNaturalZone: String
        val matchedNaturalZone: String
        val exitSpotMeter: String
        val matrixAveragePrompt: String
        val linkSpotDistanceOn: String
        val linkSpotDistanceOff: String
        val zoneOn: String
        val zoneOff: String
        val lowContrastHint: String
        val rangefinderModeTitle: String
        val inclinometerAimPrompt: String
        val eyeHeightLabel: String
        val calibrateAfOneMeter: String
        val afCalibrationScale: String
        val firstLaunchCalibrationTitle: String
        val firstLaunchCalibrationDesc: String
        val calibrateNowBtn: String
        val gotItBtn: String
    }

    private object StringsEn : Strings {
        override val appTitle = "Pro Light Meter"
        override val filmSelect = "Film Stock"
        override val spotMeter = "Spot Meter"
        override val matrixMeter = "Matrix Meter"
        override val multiSpot = "Multi-Spot"
        override val lockHold = "HOLD"
        override val unlockReading = "LOCKED"
        override val readingLocked = "READING LOCKED"
        override val liveMetering = "LIVE METERING"
        override val zoneSystem = "Zone System"
        override val rangefinder = "Rangefinder"
        override val torch = "Torch"
        override val falseColor = "False Color"
        override val compensation = "EV Comp"
        override val ndFilter = "ND Filter"
        override val logShot = "LOG SHOT"
        override val shotLogs = "Exposure Logs"
        override val reciprocityTimer = "Reciprocity Timer"
        override val framelines = "Framelines"
        override val settings = "Settings"
        override val menu = "Menu"
        override val calibrationOffset = "Metering Baseline Calibration"
        override val calibrationDesc = "Adjust baseline EV to match physical Sekonic/Gossen spot meters"
        override val reset = "Reset"
        override val language = "Language"
        override val cameraOptics = "Camera Multi-Lens & Optics"
        override val lensSwitch = "Select Physical Lens"
        override val ultraWide = "0.6x Ultra Wide"
        override val mainWide = "1.0x Main Wide"
        override val telephoto2x = "2.0x Telephoto"
        override val telephoto3x = "3.0x Portrait Tele"
        override val telephoto5x = "5.0x Super Tele"
        override val landscapeEquiv = "Landscape 35mm Equiv"
        override val portraitEquiv = "Portrait 35mm Equiv"
        override val measuredDistance = "Distance"
        override val distanceMeasuring = "Focusing distance..."
        override val infinityHyperfocal = "∞ (Infinity / Hyperfocal)"
        override val macroRange = "Macro"
        override val tapToMeasure = "Tap screen to rangefind"
        override val priorityAv = "Aperture Priority (Av)"
        override val priorityTv = "Shutter Priority (Tv)"
        override val priorityIso = "ISO Priority"
        override val priorityEvLock = "EV Match (Manual)"
        override val reciprocityComp = "Reciprocity Compensated"
        override val timerStart = "START TIMER"
        override val timerPause = "PAUSE"
        override val timerReset = "RESET"
        override val timerCompleted = "EXPOSURE COMPLETE"
        override val formatGate = "Film Format & Gate"
        override val gridGuides = "Composition Grid"
        override val colorFilters = "B&W Color Filter"
        override val digitalCropZoom = "Focal Length Frameline Crop"
        override val clearAll = "Clear All"
        override val notePlaceholder = "Add exposure notes (e.g. filter, lighting, location)..."
        override val saveLog = "Save Log"
        override val delete = "Delete"
        override val exposureValue = "Exposure Value"
        override val middleGray = "18% Middle Gray (Zone V)"

        override val cameraPermissionRequired = "Camera permission required for real-time metering"
        override val cameraPermissionDesc = "Light meter reads hardware sensor metadata to calculate accurate scene EV"
        override val grantPermission = "Grant Camera Permission"
        override val pinSpot = "Pin"
        override val apertureLabel = "Aperture (f)"
        override val shutterLabel = "Shutter (t)"
        override val isoLabel = "ISO"
        override val reciprocityBannerTitle = "Reciprocity Failure Active"
        override val reciprocityBannerFormat = "Meter: %s ➔ Real: %s (+%.1f EV)"
        override val openTimer = "Timer"
        override val distanceOn = "Range: ON"
        override val distanceOff = "Range: OFF"
        override val menuCalibration = "Menu · Calibration / Filter"
        override val outOfFovWarning = "%dmm exceeds lens (%dmm) · Tap to switch to 0.6x"
        override val switchToUltraWide = "0.6x Ultra-Wide"
        override val framelineModeMask = "Frameline Mask"
        override val framelineModeZoom = "Crop Zoom"
        override val zoneSystemTitle = "ZONE SYSTEM"
        override val alignNaturalZone = "Align Natural Z%s"
        override val matchedNaturalZone = "✓ Natural Z%s"
        override val exitSpotMeter = "Exit Spot"
        override val matrixAveragePrompt = "Frameline Matrix Metering · Tap to spot meter"
        override val linkSpotDistanceOn = "Spot-Link: ON"
        override val linkSpotDistanceOff = "Spot-Link: OFF"
        override val zoneOn = "Zone ON"
        override val zoneOff = "Zone OFF"
        override val lowContrastHint = "Low Contrast · Aim at Edge"
        override val rangefinderModeTitle = "Rangefinder Engine"
        override val inclinometerAimPrompt = "Aim crosshair at base of object on ground"
        override val eyeHeightLabel = "Camera Eye Height"
        override val calibrateAfOneMeter = "Calibrate AF at 1.0m"
        override val afCalibrationScale = "AF Scale Multiplier"
        override val firstLaunchCalibrationTitle = "💡 Metering Calibration Recommended"
        override val firstLaunchCalibrationDesc = "Due to hardware sensor & ISP variations across Android devices, we strongly recommend calibrating your baseline EV before shooting on film:\n\n1. Compare the live EV reading against a physical spot meter (Sekonic/Gossen) or an iPhone light meter app under identical lighting;\n2. Adjust the EV Baseline Calibration in Menu to match perfectly!"
        override val calibrateNowBtn = "Calibrate Now (Recommended)"
        override val gotItBtn = "Got It, Continue"
    }

    private object StringsZh : Strings {
        override val appTitle = "专业胶片测光表"
        override val filmSelect = "胶卷预设"
        override val spotMeter = "点测光"
        override val matrixMeter = "平均测光"
        override val multiSpot = "多点对比"
        override val lockHold = "锁定读数"
        override val unlockReading = "已锁定"
        override val readingLocked = "读数已锁定"
        override val liveMetering = "实时测光中"
        override val zoneSystem = "分区曝光"
        override val rangefinder = "对焦测距"
        override val torch = "补光手电"
        override val falseColor = "假色模式"
        override val compensation = "曝光补偿"
        override val ndFilter = "ND 减光镜"
        override val logShot = "记录快门"
        override val shotLogs = "曝光日志"
        override val reciprocityTimer = "倒易率长曝计时器"
        override val framelines = "画幅框线"
        override val settings = "设置"
        override val menu = "菜单"
        override val calibrationOffset = "测光基准微调"
        override val calibrationDesc = "调整基准 EV 偏移，精准校准世光/高森等物理测光表"
        override val reset = "重置"
        override val language = "显示语言 (Language)"
        override val cameraOptics = "多摄像头与焦距光学"
        override val lensSwitch = "切换物理镜头"
        override val ultraWide = "0.6x 超广角"
        override val mainWide = "1.0x 标准主摄"
        override val telephoto2x = "2.0x 长焦"
        override val telephoto3x = "3.0x 人像长焦"
        override val telephoto5x = "5.0x 超长焦"
        override val landscapeEquiv = "横屏 35mm 等效焦距"
        override val portraitEquiv = "竖屏 35mm 等效焦距"
        override val measuredDistance = "物距"
        override val distanceMeasuring = "正在对焦测距..."
        override val infinityHyperfocal = "∞ (无穷远/超焦距)"
        override val macroRange = "微距"
        override val tapToMeasure = "点击画面测距"
        override val priorityAv = "光圈优先 (Av)"
        override val priorityTv = "快门优先 (Tv)"
        override val priorityIso = "ISO 基准"
        override val priorityEvLock = "自由联动 (EV-Lock)"
        override val reciprocityComp = "倒易率补偿快门"
        override val timerStart = "启动长曝计时"
        override val timerPause = "暂停"
        override val timerReset = "重置"
        override val timerCompleted = "曝光已完成"
        override val formatGate = "胶片画幅与片门"
        override val gridGuides = "构图辅助线"
        override val colorFilters = "黑白滤镜模拟"
        override val digitalCropZoom = "焦距取景裁切联动"
        override val clearAll = "清空全部"
        override val notePlaceholder = "添加拍摄备注 (如滤镜、光照、场景)..."
        override val saveLog = "保存记录"
        override val delete = "删除"
        override val exposureValue = "曝光值"
        override val middleGray = "18% 中灰基准 (Zone V)"

        override val cameraPermissionRequired = "需要相机权限以进行实时测光与取景"
        override val cameraPermissionDesc = "测光表提取相机底层曝光元数据以计算真实环境EV"
        override val grantPermission = "授予相机权限"
        override val pinSpot = "定标"
        override val apertureLabel = "光圈 (f)"
        override val shutterLabel = "快门 (t)"
        override val isoLabel = "感光度 (ISO)"
        override val reciprocityBannerTitle = "长曝光倒易率补偿已启用"
        override val reciprocityBannerFormat = "测光: %s ➔ 补偿实拍: %s (+%.1f EV)"
        override val openTimer = "开启计时"
        override val distanceOn = "测距: 开"
        override val distanceOff = "测距: 关"
        override val menuCalibration = "菜单 · 测光标定 / 滤镜"
        override val outOfFovWarning = "%dmm 超出当前竖屏主摄(%dmm) · 点击切换超广角"
        override val switchToUltraWide = "0.6x 超广角"
        override val framelineModeMask = "取景框线模式"
        override val framelineModeZoom = "全屏裁切模式"
        override val zoneSystemTitle = "分区曝光 (ZONE SYSTEM)"
        override val alignNaturalZone = "对齐自然 Z%s"
        override val matchedNaturalZone = "✓ 匹配自然 Z%s"
        override val exitSpotMeter = "退出点测"
        override val matrixAveragePrompt = "框线内平均测光 · 点击画面开启点测"
        override val linkSpotDistanceOn = "联动点测: 开"
        override val linkSpotDistanceOff = "联动点测: 关"
        override val zoneOn = "分区 ON"
        override val zoneOff = "分区 OFF"
        override val lowContrastHint = "低反差 · 请对准边缘"
        override val rangefinderModeTitle = "测距引擎模式"
        override val inclinometerAimPrompt = "将十字准星瞄准物体与地面的接触线"
        override val eyeHeightLabel = "持机眼高 (高度)"
        override val calibrateAfOneMeter = "1.0米 AF 一键标定"
        override val afCalibrationScale = "AF 距离校准系数"
        override val firstLaunchCalibrationTitle = "💡 首次使用建议 · 测光基准标定"
        override val firstLaunchCalibrationDesc = "由于不同安卓机型的摄像头模组与 ISP 测光曝光算法存在客观兼容性差异，为确保胶片拍摄曝光 100% 精准不翻车，强烈建议在拍摄前进行一次基准校准：\n\n1. 借助实体点测光表（如世光/高森）或苹果手机测光软件，在相同光线下对准同一中灰物体测光；\n2. 在「菜单」中微调基准 EV 偏移值（如 +0.5 EV 或 -0.3 EV），使读数完全匹配即可！"
        override val calibrateNowBtn = "立即前往标定 (推荐)"
        override val gotItBtn = "我知道了，直接开始"
    }

    private object StringsZhTw : Strings {
        override val appTitle = "專業底片測光表"
        override val filmSelect = "底片預設"
        override val spotMeter = "點測光"
        override val matrixMeter = "平均測光"
        override val multiSpot = "多點對比"
        override val lockHold = "鎖定讀數"
        override val unlockReading = "已鎖定"
        override val readingLocked = "讀數已鎖定"
        override val liveMetering = "即時測光中"
        override val zoneSystem = "分區曝光"
        override val rangefinder = "對焦測距"
        override val torch = "補光手電"
        override val falseColor = "假色模式"
        override val compensation = "曝光補償"
        override val ndFilter = "ND 減光鏡"
        override val logShot = "記錄快門"
        override val shotLogs = "曝光日誌"
        override val reciprocityTimer = "倒易律長曝計時器"
        override val framelines = "畫幅框線"
        override val settings = "設定"
        override val menu = "選單"
        override val calibrationOffset = "測光基準微調"
        override val calibrationDesc = "調整基準 EV 偏移，精準校準世光/高森等物理測光表"
        override val reset = "重置"
        override val language = "顯示語言 (Language)"
        override val cameraOptics = "多鏡頭與焦距光學"
        override val lensSwitch = "切換物理鏡頭"
        override val ultraWide = "0.6x 超廣角"
        override val mainWide = "1.0x 標準主鏡"
        override val telephoto2x = "2.0x 長焦"
        override val telephoto3x = "3.0x 人像長焦"
        override val telephoto5x = "5.0x 超長焦"
        override val landscapeEquiv = "橫向 35mm 等效焦距"
        override val portraitEquiv = "直向 35mm 等效焦距"
        override val measuredDistance = "物距"
        override val distanceMeasuring = "正在對焦測距..."
        override val infinityHyperfocal = "∞ (無限遠/超焦距)"
        override val macroRange = "微距"
        override val tapToMeasure = "點擊畫面測距"
        override val priorityAv = "光圈先決 (Av)"
        override val priorityTv = "快門先決 (Tv)"
        override val priorityIso = "ISO 基準"
        override val priorityEvLock = "自由連動 (EV-Lock)"
        override val reciprocityComp = "倒易律補償快門"
        override val timerStart = "啟動長曝計時"
        override val timerPause = "暫停"
        override val timerReset = "重置"
        override val timerCompleted = "曝光已完成"
        override val formatGate = "底片畫幅與片門"
        override val gridGuides = "構圖輔助線"
        override val colorFilters = "黑白濾鏡模擬"
        override val digitalCropZoom = "焦距取景裁切連動"
        override val clearAll = "清空全部"
        override val notePlaceholder = "新增拍攝備註 (如濾鏡、光照、場景)..."
        override val saveLog = "儲存記錄"
        override val delete = "刪除"
        override val exposureValue = "曝光值"
        override val middleGray = "18% 中灰基準 (Zone V)"

        override val cameraPermissionRequired = "需要相機權限以進行即時測光與取景"
        override val cameraPermissionDesc = "測光表提取相機底層曝光元資料以計算真實環境EV"
        override val grantPermission = "授予相機權限"
        override val pinSpot = "定標"
        override val apertureLabel = "光圈 (f)"
        override val shutterLabel = "快門 (t)"
        override val isoLabel = "感光度 (ISO)"
        override val reciprocityBannerTitle = "長曝光倒易律補償已啟用"
        override val reciprocityBannerFormat = "測光: %s ➔ 補償實拍: %s (+%.1f EV)"
        override val openTimer = "開啟計時"
        override val distanceOn = "測距: 開"
        override val distanceOff = "測距: 關"
        override val menuCalibration = "選單 · 測光標定 / 濾鏡"
        override val outOfFovWarning = "%dmm 超出當前直向主鏡(%dmm) · 點擊切換超廣角"
        override val switchToUltraWide = "0.6x 超廣角"
        override val framelineModeMask = "取景框線模式"
        override val framelineModeZoom = "全螢幕裁切模式"
        override val zoneSystemTitle = "分區曝光 (ZONE SYSTEM)"
        override val alignNaturalZone = "對齊自然 Z%s"
        override val matchedNaturalZone = "✓ 匹配自然 Z%s"
        override val exitSpotMeter = "結束點測"
        override val matrixAveragePrompt = "框線內平均測光 · 點擊畫面開啟點測"
        override val linkSpotDistanceOn = "連動點測: 開"
        override val linkSpotDistanceOff = "連動點測: 關"
        override val zoneOn = "分區 ON"
        override val zoneOff = "分區 OFF"
        override val lowContrastHint = "低反差 · 請對準邊緣"
        override val rangefinderModeTitle = "測距引擎模式"
        override val inclinometerAimPrompt = "將十字準星瞄準物體與地面的接觸線"
        override val eyeHeightLabel = "持機眼高 (高度)"
        override val calibrateAfOneMeter = "1.0米 AF 一鍵標定"
        override val afCalibrationScale = "AF 距離校準係數"
        override val firstLaunchCalibrationTitle = "💡 首次使用建議 · 測光基準標定"
        override val firstLaunchCalibrationDesc = "由於不同安卓機型的相機模組與 ISP 測光曝光演算法存在客觀相容性差異，為確保底片拍攝曝光 100% 精準不翻車，強烈建議在拍攝前進行一次基準校準：\n\n1. 借助實體點測光表（如世光/高森）或蘋果手機測光軟體，在相同光線下對準同一中灰物體測光；\n2. 在「選單」中微調基準 EV 偏移值（如 +0.5 EV 或 -0.3 EV），使讀數完全匹配即可！"
        override val calibrateNowBtn = "立即前往標定 (推薦)"
        override val gotItBtn = "我知道了，直接開始"
    }

    private object StringsJa : Strings {
        override val appTitle = "プロ露出計"
        override val filmSelect = "フィルム選択"
        override val spotMeter = "スポット測光"
        override val matrixMeter = "中央平均測光"
        override val multiSpot = "マルチスポット"
        override val lockHold = "ホールド"
        override val unlockReading = "ロック中"
        override val readingLocked = "測定値を固定中"
        override val liveMetering = "ライブ測光中"
        override val zoneSystem = "ゾーンシステム"
        override val rangefinder = "測距計"
        override val torch = "ライト"
        override val falseColor = "フォールスカラー"
        override val compensation = "露出補正"
        override val ndFilter = "NDフィルター"
        override val logShot = "記録"
        override val shotLogs = "露出ログ"
        override val reciprocityTimer = "相反則不軌タイマー"
        override val framelines = "フレームライン"
        override val settings = "設定"
        override val menu = "メニュー"
        override val calibrationOffset = "露出基準キャリブレーション"
        override val calibrationDesc = "セコニックやゴッセン等の単体露出計に合わせて基準EVを微調整"
        override val reset = "リセット"
        override val language = "言語 (Language)"
        override val cameraOptics = "カメラレンズと光学系"
        override val lensSwitch = "レンズ切り替え"
        override val ultraWide = "0.6x 超広角"
        override val mainWide = "1.0x 標準広角"
        override val telephoto2x = "2.0x 望遠"
        override val telephoto3x = "3.0x ポートレート望遠"
        override val telephoto5x = "5.0x 超望遠"
        override val landscapeEquiv = "横向き 35mm 換算"
        override val portraitEquiv = "縦向き 35mm 換算"
        override val measuredDistance = "被写体距離"
        override val distanceMeasuring = "測距中..."
        override val infinityHyperfocal = "∞ (無限遠 / パンフォーカス)"
        override val macroRange = "マクロ"
        override val tapToMeasure = "画面タップで測距"
        override val priorityAv = "絞り優先 (Av)"
        override val priorityTv = "シャッター優先 (Tv)"
        override val priorityIso = "ISO 優先"
        override val priorityEvLock = "手動連動 (EV-Lock)"
        override val reciprocityComp = "相反則補正シャッター"
        override val timerStart = "タイマー開始"
        override val timerPause = "一時停止"
        override val timerReset = "リセット"
        override val timerCompleted = "露光完了"
        override val formatGate = "フィルム判型とゲート"
        override val gridGuides = "構図グリッド"
        override val colorFilters = "モノクロ用カラーフィルター"
        override val digitalCropZoom = "焦点距離フレームクロップ"
        override val clearAll = "すべて消去"
        override val notePlaceholder = "撮影メモを追加..."
        override val saveLog = "保存"
        override val delete = "削除"
        override val exposureValue = "露出値 (EV)"
        override val middleGray = "18% 標準反射率 (Zone V)"

        override val cameraPermissionRequired = "リアルタイム測光のためにカメラの権限が必要です"
        override val cameraPermissionDesc = "センサーのメタデータを読み取って正確なEVを算出します"
        override val grantPermission = "カメラの権限を許可"
        override val pinSpot = "固定"
        override val apertureLabel = "絞り (f)"
        override val shutterLabel = "シャッター (t)"
        override val isoLabel = "ISO"
        override val reciprocityBannerTitle = "相反則不軌補正が有効"
        override val reciprocityBannerFormat = "測光値: %s ➔ 補正実効: %s (+%.1f EV)"
        override val openTimer = "タイマー"
        override val distanceOn = "測距: ON"
        override val distanceOff = "測距: OFF"
        override val menuCalibration = "メニュー · キャリブレーション / フィルター"
        override val outOfFovWarning = "%dmm は現在の縦向き画角 (%dmm) を超えています"
        override val switchToUltraWide = "0.6x 超広角へ切り替え"
        override val framelineModeMask = "フレームマスク"
        override val framelineModeZoom = "クロップズーム"
        override val zoneSystemTitle = "ゾーンシステム"
        override val alignNaturalZone = "自然光に合わせる Z%s"
        override val matchedNaturalZone = "✓ 自然光一致 Z%s"
        override val exitSpotMeter = "スポット終了"
        override val matrixAveragePrompt = "フレーム内平均測光 · タップでスポット測光"
        override val linkSpotDistanceOn = "スポット連動: ON"
        override val linkSpotDistanceOff = "スポット連動: OFF"
        override val zoneOn = "ゾーン ON"
        override val zoneOff = "ゾーン OFF"
        override val lowContrastHint = "低コントラスト · エッジに合わせてください"
        override val rangefinderModeTitle = "測距エンジン"
        override val inclinometerAimPrompt = "十字線を被写体の接地線に合わせてください"
        override val eyeHeightLabel = "撮影者の目線の高さ"
        override val calibrateAfOneMeter = "1.0m AF ワンタップ校正"
        override val afCalibrationScale = "AF 距離補正係数"
        override val firstLaunchCalibrationTitle = "💡 初回使用時の推奨事項 · 露出基準校正"
        override val firstLaunchCalibrationDesc = "Android端末によりカメラやISP露出特性が異なるため、実写前に基準EVの校正を推奨します:\n\n1. 単体露出計やiPhone露出計アプリと同一環境で比較\n2. 「メニュー」の基準EVオフセットで数値を合わせてください"
        override val calibrateNowBtn = "今すぐ校正 (推奨)"
        override val gotItBtn = "了解して開始"
    }

    private object StringsKo : Strings {
        override val appTitle = "프로 노출계"
        override val filmSelect = "필름 선택"
        override val spotMeter = "스팟 측광"
        override val matrixMeter = "평균 측광"
        override val multiSpot = "다중 스팟"
        override val lockHold = "고정"
        override val unlockReading = "고정됨"
        override val readingLocked = "측정값 고정됨"
        override val liveMetering = "실시간 측광 중"
        override val zoneSystem = "존 시스템"
        override val rangefinder = "거리계"
        override val torch = "플래시 라이트"
        override val falseColor = "폴스 컬러"
        override val compensation = "노출 보정"
        override val ndFilter = "ND 필터"
        override val logShot = "기록"
        override val shotLogs = "노출 로그"
        override val reciprocityTimer = "상반칙 불궤 타이머"
        override val framelines = "프레임 라인"
        override val settings = "설정"
        override val menu = "메뉴"
        override val calibrationOffset = "노출 기준 캘리브레이션"
        override val calibrationDesc = "세코닉/고센 노출계에 맞게 기준 EV 미세 조정"
        override val reset = "초기화"
        override val language = "언어 (Language)"
        override val cameraOptics = "카메라 렌즈 및 광학계"
        override val lensSwitch = "렌즈 전환"
        override val ultraWide = "0.6x 초광각"
        override val mainWide = "1.0x 표준 광각"
        override val telephoto2x = "2.0x 망원"
        override val telephoto3x = "3.0x 인물 망원"
        override val telephoto5x = "5.0x 초망원"
        override val landscapeEquiv = "가로 35mm 환산"
        override val portraitEquiv = "세로 35mm 환산"
        override val measuredDistance = "거리"
        override val distanceMeasuring = "거리 측정 중..."
        override val infinityHyperfocal = "∞ (무한대 / 과초점)"
        override val macroRange = "접사"
        override val tapToMeasure = "화면 터치하여 거리 측정"
        override val priorityAv = "조리개 우선 (Av)"
        override val priorityTv = "셔터 우선 (Tv)"
        override val priorityIso = "ISO 우선"
        override val priorityEvLock = "수동 연동 (EV-Lock)"
        override val reciprocityComp = "상반칙 보정 셔터"
        override val timerStart = "타이머 시작"
        override val timerPause = "일시정지"
        override val timerReset = "초기화"
        override val timerCompleted = "노출 완료"
        override val formatGate = "필름 판형 및 게이트"
        override val gridGuides = "구도 그리드"
        override val colorFilters = "흑백 컬러 필터"
        override val digitalCropZoom = "초점거리 프레임 크롭"
        override val clearAll = "모두 삭제"
        override val notePlaceholder = "촬영 메모 추가 (필터, 조명 등)..."
        override val saveLog = "저장"
        override val delete = "삭제"
        override val exposureValue = "노출값 (EV)"
        override val middleGray = "18% 중간 회색 (Zone V)"

        override val cameraPermissionRequired = "실시간 측광 및 뷰파인더를 위해 카메라 권한이 필요합니다"
        override val cameraPermissionDesc = "하드웨어 센서 메타데이터를 기반으로 정확한 EV를 계산합니다"
        override val grantPermission = "카메라 권한 허용"
        override val pinSpot = "고정"
        override val apertureLabel = "조리개 (f)"
        override val shutterLabel = "셔터 (t)"
        override val isoLabel = "ISO"
        override val reciprocityBannerTitle = "상반칙 불궤 보정 활성화"
        override val reciprocityBannerFormat = "측광: %s ➔ 보정 실촬영: %s (+%.1f EV)"
        override val openTimer = "타이머 시작"
        override val distanceOn = "측거리: 켬"
        override val distanceOff = "측거리: 끔"
        override val menuCalibration = "메뉴 · 캘리브레이션 / 필터"
        override val outOfFovWarning = "%dmm 화각 초과 (%dmm) · 0.6x 초광각으로 전환"
        override val switchToUltraWide = "0.6x 초광각"
        override val framelineModeMask = "프레임 마스크"
        override val framelineModeZoom = "크롭 줌"
        override val zoneSystemTitle = "존 시스템"
        override val alignNaturalZone = "자연광 맞춤 Z%s"
        override val matchedNaturalZone = "✓ 자연광 Z%s"
        override val exitSpotMeter = "스팟 해제"
        override val matrixAveragePrompt = "프레임 내 평균 측광 · 터치하여 스팟 측광"
        override val linkSpotDistanceOn = "스팟 연동: 켬"
        override val linkSpotDistanceOff = "스팟 연동: 끔"
        override val zoneOn = "존 ON"
        override val zoneOff = "존 OFF"
        override val lowContrastHint = "저대비 · 가장자리에 맞추세요"
        override val rangefinderModeTitle = "거리계 엔진"
        override val inclinometerAimPrompt = "십자선을 피사체의 지면 접촉선에 맞추세요"
        override val eyeHeightLabel = "촬영자 눈높이"
        override val calibrateAfOneMeter = "1.0m AF 원터치 캘리브레이션"
        override val afCalibrationScale = "AF 거리 보정 계수"
        override val firstLaunchCalibrationTitle = "💡 첫 사용 권장 · 노출 기준 캘리브레이션"
        override val firstLaunchCalibrationDesc = "안드로이드 기기별 센서와 ISP 특성이 다르므로 촬영 전 기준 EV를 캘리브레이션하는 것을 적극 권장합니다:\n\n1. 세코닉/고센 노출계 또는 iPhone 노출계 앱과 동일 환경에서 비교\n2. 「메뉴」에서 기준 EV 오프셋을 조정하여 일치시키세요"
        override val calibrateNowBtn = "지금 캘리브레이션 (권장)"
        override val gotItBtn = "확인하고 시작"
    }

    private object StringsFr : Strings {
        override val appTitle = "Posemètre Pro"
        override val filmSelect = "Film"
        override val spotMeter = "Mesure Spot"
        override val matrixMeter = "Mesure Matricielle"
        override val multiSpot = "Multi-Spot"
        override val lockHold = "MÉMO"
        override val unlockReading = "VERROUILLÉ"
        override val readingLocked = "VALEUR VERROUILLÉE"
        override val liveMetering = "MESURE EN DIRECT"
        override val zoneSystem = "Zone System"
        override val rangefinder = "Télémètre"
        override val torch = "Lampe"
        override val falseColor = "Fausses Couleurs"
        override val compensation = "Comp. EV"
        override val ndFilter = "Filtre ND"
        override val logShot = "ENREGISTRER"
        override val shotLogs = "Journal d'Exposition"
        override val reciprocityTimer = "Minuteur Réciprocité"
        override val framelines = "Cadres de Visée"
        override val settings = "Paramètres"
        override val menu = "Menu"
        override val calibrationOffset = "Étalonnage Base EV"
        override val calibrationDesc = "Ajuster l'offset EV de base pour étalonner avec Sekonic / Gossen"
        override val reset = "Réinitialiser"
        override val language = "Langue"
        override val cameraOptics = "Optiques de l'Appareil"
        override val lensSwitch = "Changer d'Objectif"
        override val ultraWide = "0.6x Ultra Grand-Angle"
        override val mainWide = "1.0x Grand-Angle Principal"
        override val telephoto2x = "2.0x Téléobjectif"
        override val telephoto3x = "3.0x Télé Portrait"
        override val telephoto5x = "5.0x Super Télé"
        override val landscapeEquiv = "Équiv. 35mm Paysage"
        override val portraitEquiv = "Équiv. 35mm Portrait"
        override val measuredDistance = "Distance"
        override val distanceMeasuring = "Mise au point télémétrique..."
        override val infinityHyperfocal = "∞ (Infini / Hyperfocale)"
        override val macroRange = "Macro"
        override val tapToMeasure = "Toucher pour mesurer la distance"
        override val priorityAv = "Priorité Ouverture (Av)"
        override val priorityTv = "Priorité Vitesse (Tv)"
        override val priorityIso = "Priorité ISO"
        override val priorityEvLock = "Manuel (EV-Lock)"
        override val reciprocityComp = "Vitesse compensée Schwarzschild"
        override val timerStart = "DÉMARRER MINUTEUR"
        override val timerPause = "PAUSE"
        override val timerReset = "RÉINITIALISER"
        override val timerCompleted = "EXPOSITION TERMINÉE"
        override val formatGate = "Format et Fenêtre du Film"
        override val gridGuides = "Grille de Composition"
        override val colorFilters = "Filtres Noir et Blanc"
        override val digitalCropZoom = "Recadrage Focale du Viseur"
        override val clearAll = "Tout effacer"
        override val notePlaceholder = "Ajouter des notes d'exposition..."
        override val saveLog = "Enregistrer"
        override val delete = "Supprimer"
        override val exposureValue = "Indice de Lumination (EV)"
        override val middleGray = "Gris Neutre 18% (Zone V)"

        override val cameraPermissionRequired = "Autorisation caméra requise pour la mesure en direct"
        override val cameraPermissionDesc = "Lit les métadonnées matérielles pour calculer l'EV réel"
        override val grantPermission = "Autoriser la Caméra"
        override val pinSpot = "Épingler"
        override val apertureLabel = "Ouverture (f)"
        override val shutterLabel = "Vitesse (t)"
        override val isoLabel = "ISO"
        override val reciprocityBannerTitle = "Compensation de Réciprocité Active"
        override val reciprocityBannerFormat = "Mesure: %s ➔ Réel: %s (+%.1f EV)"
        override val openTimer = "Minuteur"
        override val distanceOn = "Distance: ON"
        override val distanceOff = "Distance: OFF"
        override val menuCalibration = "Menu · Étalonnage / Filtres"
        override val outOfFovWarning = "%dmm dépasse l'optique (%dmm) · Passer à 0.6x"
        override val switchToUltraWide = "0.6x Ultra Grand-Angle"
        override val framelineModeMask = "Masque de Cadrage"
        override val framelineModeZoom = "Zoom Recradé"
        override val zoneSystemTitle = "ZONE SYSTEM"
        override val alignNaturalZone = "Aligner Naturel Z%s"
        override val matchedNaturalZone = "✓ Naturel Z%s"
        override val exitSpotMeter = "Quitter Spot"
        override val matrixAveragePrompt = "Mesure Moyenne dans le Cadre · Toucher pour Spot"
        override val linkSpotDistanceOn = "Liaison Spot: ON"
        override val linkSpotDistanceOff = "Liaison Spot: OFF"
        override val zoneOn = "Zone ON"
        override val zoneOff = "Zone OFF"
        override val lowContrastHint = "Faible contraste · Viser un bord"
        override val rangefinderModeTitle = "Moteur Télémétrique"
        override val inclinometerAimPrompt = "Viser la ligne de contact au sol de l'objet"
        override val eyeHeightLabel = "Hauteur des yeux (appareil)"
        override val calibrateAfOneMeter = "Étalonner AF à 1.0m"
        override val afCalibrationScale = "Facteur d'échelle AF"
        override val firstLaunchCalibrationTitle = "💡 Conseil de première utilisation · Étalonnage"
        override val firstLaunchCalibrationDesc = "Les capteurs Android variant selon les fabricants, nous vous recommandons d'étalonner la mesure EV de base avant votre première prise de vue:\n\n1. Comparez la mesure avec un posemètre dédié (Sekonic/Gossen) ou une app iPhone sous le même éclairage;\n2. Ajustez l'Étalonnage EV dans le Menu!"
        override val calibrateNowBtn = "Étalonner maintenant"
        override val gotItBtn = "Compris, continuer"
    }

    private object StringsEs : Strings {
        override val appTitle = "Fotómetro Pro"
        override val filmSelect = "Tipo de Película"
        override val spotMeter = "Medición Puntual"
        override val matrixMeter = "Medición Matricial"
        override val multiSpot = "Multi-Punto"
        override val lockHold = "BLOQUEAR"
        override val unlockReading = "BLOQUEADO"
        override val readingLocked = "LECTURA BLOQUEADA"
        override val liveMetering = "MEDICIÓN EN VIVO"
        override val zoneSystem = "Sistema de Zonas"
        override val rangefinder = "Telémetro"
        override val torch = "Linterna"
        override val falseColor = "Falso Color"
        override val compensation = "Comp. EV"
        override val ndFilter = "Filtro ND"
        override val logShot = "GUARDAR TOMA"
        override val shotLogs = "Registro de Exposición"
        override val reciprocityTimer = "Temporizador de Reciprocidad"
        override val framelines = "Marcos de Encuadre"
        override val settings = "Ajustes"
        override val menu = "Menú"
        override val calibrationOffset = "Calibración Base EV"
        override val calibrationDesc = "Ajustar EV base para calibrar con fotómetros Sekonic / Gossen"
        override val reset = "Restablecer"
        override val language = "Idioma"
        override val cameraOptics = "Cámara y Ópticas"
        override val lensSwitch = "Cambiar Lente"
        override val ultraWide = "0.6x Ultra Gran Angular"
        override val mainWide = "1.0x Gran Angular Principal"
        override val telephoto2x = "2.0x Teleobjetivo"
        override val telephoto3x = "3.0x Tele Retrato"
        override val telephoto5x = "5.0x Súper Tele"
        override val landscapeEquiv = "Equiv. 35mm Paisaje"
        override val portraitEquiv = "Equiv. 35mm Retrato"
        override val measuredDistance = "Distancia"
        override val distanceMeasuring = "Enfocando distancia..."
        override val infinityHyperfocal = "∞ (Infinito / Hiperfocal)"
        override val macroRange = "Macro"
        override val tapToMeasure = "Tocar para medir distancia"
        override val priorityAv = "Prioridad Apertura (Av)"
        override val priorityTv = "Prioridad Obturación (Tv)"
        override val priorityIso = "Prioridad ISO"
        override val priorityEvLock = "Manual (EV-Lock)"
        override val reciprocityComp = "Obturación compensada Schwarzschild"
        override val timerStart = "INICIAR TEMPORIZADOR"
        override val timerPause = "PAUSA"
        override val timerReset = "RESTABLECER"
        override val timerCompleted = "EXPOSICIÓN COMPLETADA"
        override val formatGate = "Formato y Ventana de Película"
        override val gridGuides = "Guías de Composición"
        override val colorFilters = "Filtros B&N"
        override val digitalCropZoom = "Recorte de Encuadre Focal"
        override val clearAll = "Borrar Todo"
        override val notePlaceholder = "Añadir notas de exposición..."
        override val saveLog = "Guardar"
        override val delete = "Eliminar"
        override val exposureValue = "Valor de Exposición (EV)"
        override val middleGray = "Gris Neutro 18% (Zona V)"

        override val cameraPermissionRequired = "Se requiere permiso de cámara para la medición en vivo"
        override val cameraPermissionDesc = "Lee los metadatos del sensor para calcular el valor EV real de la escena"
        override val grantPermission = "Conceder Permiso de Cámara"
        override val pinSpot = "Fijar"
        override val apertureLabel = "Apertura (f)"
        override val shutterLabel = "Obturador (t)"
        override val isoLabel = "ISO"
        override val reciprocityBannerTitle = "Compensación de Reciprocidad Activa"
        override val reciprocityBannerFormat = "Medido: %s ➔ Real: %s (+%.1f EV)"
        override val openTimer = "Temporizador"
        override val distanceOn = "Distancia: ON"
        override val distanceOff = "Distancia: OFF"
        override val menuCalibration = "Menú · Calibración / Filtros"
        override val outOfFovWarning = "%dmm excede lente (%dmm) · Tocar para cambiar a 0.6x"
        override val switchToUltraWide = "0.6x Ultra Gran Angular"
        override val framelineModeMask = "Máscara de Encuadre"
        override val framelineModeZoom = "Zoom Recorte"
        override val zoneSystemTitle = "SISTEMA DE ZONAS"
        override val alignNaturalZone = "Alinear Natural Z%s"
        override val matchedNaturalZone = "✓ Natural Z%s"
        override val exitSpotMeter = "Salir Puntual"
        override val matrixAveragePrompt = "Medición Promedio en Cuadro · Tocar para Puntual"
        override val linkSpotDistanceOn = "Vincular Punto: ON"
        override val linkSpotDistanceOff = "Vincular Punto: OFF"
        override val zoneOn = "Zona ON"
        override val zoneOff = "Zona OFF"
        override val lowContrastHint = "Bajo contraste · Apunte al borde"
        override val rangefinderModeTitle = "Motor de Telémetro"
        override val inclinometerAimPrompt = "Apuntar retícula a la base del objeto en el suelo"
        override val eyeHeightLabel = "Altura de ojos (cámara)"
        override val calibrateAfOneMeter = "Calibrar AF a 1.0m"
        override val afCalibrationScale = "Escala de distancia AF"
        override val firstLaunchCalibrationTitle = "💡 Recomendación de primer uso · Calibración EV"
        override val firstLaunchCalibrationDesc = "Dado que los sensores varían entre dispositivos Android, recomendamos calibrar el EV base antes de disparar con película:\n\n1. Compare con un fotómetro físico (Sekonic/Gossen) o app de iPhone bajo la misma luz;\n2. ¡Ajuste el desplazamiento EV en el Menú para igualarlo!"
        override val calibrateNowBtn = "Calibrar ahora (Recomendado)"
        override val gotItBtn = "Entendido, continuar"
    }

    private object StringsDe : Strings {
        override val appTitle = "Pro Belichtungsmesser"
        override val filmSelect = "Filmtyp"
        override val spotMeter = "Spotmessung"
        override val matrixMeter = "Matrixmessung"
        override val multiSpot = "Multi-Spot"
        override val lockHold = "HALTEN"
        override val unlockReading = "GESPERRT"
        override val readingLocked = "MESSWERT GESPERRT"
        override val liveMetering = "LIVE-MESSUNG"
        override val zoneSystem = "Zonensystem"
        override val rangefinder = "Entfernungsmesser"
        override val torch = "Taschenlampe"
        override val falseColor = "Falschfarben"
        override val compensation = "EV-Korr."
        override val ndFilter = "ND-Filter"
        override val logShot = "SPEICHERN"
        override val shotLogs = "Belichtungsprotokoll"
        override val reciprocityTimer = "Schwarzschild-Timer"
        override val framelines = "Sucherrahmen"
        override val settings = "Einstellungen"
        override val menu = "Menü"
        override val calibrationOffset = "EV-Basis-Kalibrierung"
        override val calibrationDesc = "Basis-EV anpassen für Sekonic / Gossen Handbelichtungsmesser"
        override val reset = "Zurücksetzen"
        override val language = "Sprache (Language)"
        override val cameraOptics = "Kamera-Optik & Objektive"
        override val lensSwitch = "Objektiv wechseln"
        override val ultraWide = "0.6x Ultraweitwinkel"
        override val mainWide = "1.0x Haupt-Weitwinkel"
        override val telephoto2x = "2.0x Teleobjektiv"
        override val telephoto3x = "3.0x Porträt-Tele"
        override val telephoto5x = "5.0x Super-Tele"
        override val landscapeEquiv = "Querformat 35mm Äquiv."
        override val portraitEquiv = "Hochformat 35mm Äquiv."
        override val measuredDistance = "Distanz"
        override val distanceMeasuring = "Entfernungsmessung..."
        override val infinityHyperfocal = "∞ (Unendlich / Hyperfokal)"
        override val macroRange = "Makro"
        override val tapToMeasure = "Tippen für Distanzmessung"
        override val priorityAv = "Zeitautomatik (Av)"
        override val priorityTv = "Blendenautomatik (Tv)"
        override val priorityIso = "ISO-Priorität"
        override val priorityEvLock = "Manuell (EV-Lock)"
        override val reciprocityComp = "Schwarzschild-kompensierte Belichtungszeit"
        override val timerStart = "TIMER STARTEN"
        override val timerPause = "PAUSE"
        override val timerReset = "ZURÜCKSETZEN"
        override val timerCompleted = "BELICHTUNG BEENDET"
        override val formatGate = "Filmformat & Bildfenster"
        override val gridGuides = "Kompositionsgitter"
        override val colorFilters = "S/W Farbfilter"
        override val digitalCropZoom = "Brennweiten-Sucherbeschnitt"
        override val clearAll = "Alles löschen"
        override val notePlaceholder = "Belichtungsnotizen hinzufügen..."
        override val saveLog = "Speichern"
        override val delete = "Löschen"
        override val exposureValue = "Lichtwert (EV)"
        override val middleGray = "18% Mittelgrau (Zone V)"

        override val cameraPermissionRequired = "Kamerazugriff für Live-Belichtungsmessung erforderlich"
        override val cameraPermissionDesc = "Liest Hardware-Sensordaten zur genauen Berechnung des Lichtwerts (EV)"
        override val grantPermission = "Kamerazugriff erlauben"
        override val pinSpot = "Fixieren"
        override val apertureLabel = "Blende (f)"
        override val shutterLabel = "Zeit (t)"
        override val isoLabel = "ISO"
        override val reciprocityBannerTitle = "Schwarzschild-Kompensation aktiv"
        override val reciprocityBannerFormat = "Gemessen: %s ➔ Real: %s (+%.1f EV)"
        override val openTimer = "Timer"
        override val distanceOn = "Distanz: EIN"
        override val distanceOff = "Distanz: AUS"
        override val menuCalibration = "Menü · Kalibrierung / Filter"
        override val outOfFovWarning = "%dmm überschreitet Objektiv (%dmm) · Auf 0.6x wechseln"
        override val switchToUltraWide = "0.6x Ultraweitwinkel"
        override val framelineModeMask = "Rahmenmaske"
        override val framelineModeZoom = "Zoom-Beschnitt"
        override val zoneSystemTitle = "ZONENSYSTEM"
        override val alignNaturalZone = "Natürlich anpassen Z%s"
        override val matchedNaturalZone = "✓ Natürlich Z%s"
        override val exitSpotMeter = "Spot beenden"
        override val matrixAveragePrompt = "Mittenbetonte Messung im Rahmen · Tippen für Spot"
        override val linkSpotDistanceOn = "Spot-Link: EIN"
        override val linkSpotDistanceOff = "Spot-Link: AUS"
        override val zoneOn = "Zone EIN"
        override val zoneOff = "Zone AUS"
        override val lowContrastHint = "Geringer Kontrast · Kante anvisieren"
        override val rangefinderModeTitle = "Entfernungsmesser-Modus"
        override val inclinometerAimPrompt = "Fadenkreuz auf Bodenkontaktlinie des Objekts richten"
        override val eyeHeightLabel = "Kamerahöhe / Augenhöhe"
        override val calibrateAfOneMeter = "1.0m AF 1-Tipp Kalibrierung"
        override val afCalibrationScale = "AF-Distanzfaktor"
        override val firstLaunchCalibrationTitle = "💡 Empfehlung vor erster Nutzung · Kalibrierung"
        override val firstLaunchCalibrationDesc = "Da Kamerasensoren variieren, empfehlen wir die Kalibrierung des Basis-EV vor der ersten Filmaufnahme:\n\n1. Vergleichen Sie den Wert mit einem Sekonic/Gossen oder einer iPhone-App;\n2. Passen Sie den Basis-EV-Offset im Menü an!"
        override val calibrateNowBtn = "Jetzt kalibrieren"
        override val gotItBtn = "Verstanden, weiter"
    }

    private object StringsRu : Strings {
        override val appTitle = "Про Экспонометр"
        override val filmSelect = "Плёнка"
        override val spotMeter = "Точечный"
        override val matrixMeter = "Матричный"
        override val multiSpot = "Мульти-Точка"
        override val lockHold = "ФИКСАЦИЯ"
        override val unlockReading = "ЗАФИКСИРОВАНО"
        override val readingLocked = "ЗНАЧЕНИЕ ЗАФИКСИРОВАНО"
        override val liveMetering = "ЖИВОЙ ЗАМЕР"
        override val zoneSystem = "Зонная Система"
        override val rangefinder = "Дальномер"
        override val torch = "Фонарик"
        override val falseColor = "Ложный Цвет"
        override val compensation = "Экспокоррекция"
        override val ndFilter = "ND Фильтр"
        override val logShot = "ЗАПИСАТЬ КАДР"
        override val shotLogs = "Журнал Экспозиций"
        override val reciprocityTimer = "Таймер Эффекта Шварцшильда"
        override val framelines = "Рамки Кадрирования"
        override val settings = "Настройки"
        override val menu = "Меню"
        override val calibrationOffset = "Калибровка Базового EV"
        override val calibrationDesc = "Точная калибровка под физические экспонометры Sekonic / Gossen"
        override val reset = "Сброс"
        override val language = "Язык (Language)"
        override val cameraOptics = "Камеры и Оптика"
        override val lensSwitch = "Выбор Объектива"
        override val ultraWide = "0.6x Сверхширокоугольный"
        override val mainWide = "1.0x Основной Широкоугольный"
        override val telephoto2x = "2.0x Телеобъектив"
        override val telephoto3x = "3.0x Портретный Теле"
        override val telephoto5x = "5.0x Супер-Теле"
        override val landscapeEquiv = "Альбомный 35мм эквив."
        override val portraitEquiv = "Портретный 35мм эквив."
        override val measuredDistance = "Дистанция"
        override val distanceMeasuring = "Замер дистанции..."
        override val infinityHyperfocal = "∞ (Бесконечность / Гиперфокал)"
        override val macroRange = "Макро"
        override val tapToMeasure = "Коснитесь для замера"
        override val priorityAv = "Приоритет Диафрагмы (Av)"
        override val priorityTv = "Приоритет Выдержки (Tv)"
        override val priorityIso = "Приоритет ISO"
        override val priorityEvLock = "Ручной (EV-Lock)"
        override val reciprocityComp = "Скорректированная выдержка Шварцшильда"
        override val timerStart = "СТАРТ ТАЙМЕРА"
        override val timerPause = "ПАУЗА"
        override val timerReset = "СБРОС"
        override val timerCompleted = "ЭКСПОЗИЦИЯ ЗАВЕРШЕНА"
        override val formatGate = "Формат Плёнки и Кадра"
        override val gridGuides = "Сетка Композиции"
        override val colorFilters = "Ч/Б Светофильтры"
        override val digitalCropZoom = "Кадрирование Фокусного Расстояния"
        override val clearAll = "Очистить всё"
        override val notePlaceholder = "Добавить примечания к кадру..."
        override val saveLog = "Сохранить"
        override val delete = "Удалить"
        override val exposureValue = "Экспозиционное Число (EV)"
        override val middleGray = "18% Нейтрально-серый (Зона V)"

        override val cameraPermissionRequired = "Требуется доступ к камере для замера экспозиции"
        override val cameraPermissionDesc = "Использует метаданные сенсора для вычисления точного значения EV сцены"
        override val grantPermission = "Разрешить доступ к камере"
        override val pinSpot = "Точка"
        override val apertureLabel = "Диафрагма (f)"
        override val shutterLabel = "Выдержка (t)"
        override val isoLabel = "ISO"
        override val reciprocityBannerTitle = "Поправка Шварцшильда активна"
        override val reciprocityBannerFormat = "Замер: %s ➔ С поправкой: %s (+%.1f EV)"
        override val openTimer = "Таймер"
        override val distanceOn = "Дальномер: ВКЛ"
        override val distanceOff = "Дальномер: ВЫКЛ"
        override val menuCalibration = "Меню · Калибровка / Фильтры"
        override val outOfFovWarning = "%dмм шире угла камеры (%dмм) · Нажмите для 0.6x"
        override val switchToUltraWide = "0.6x Сверхширокоугольный"
        override val framelineModeMask = "Рамка Кадрирования"
        override val framelineModeZoom = "Зум Кадрирование"
        override val zoneSystemTitle = "ЗОННАЯ СИСТЕМА"
        override val alignNaturalZone = "К натуральной Z%s"
        override val matchedNaturalZone = "✓ Натуральная Z%s"
        override val exitSpotMeter = "Выйти из точки"
        override val matrixAveragePrompt = "Матричный замер в рамке · Нажмите для точечного"
        override val linkSpotDistanceOn = "Связь точки: ВКЛ"
        override val linkSpotDistanceOff = "Связь точки: ВЫКЛ"
        override val zoneOn = "Зоны ВКЛ"
        override val zoneOff = "Зоны ВЫКЛ"
        override val lowContrastHint = "Низкий контраст · Наведите на край"
        override val rangefinderModeTitle = "Режим Дальномера"
        override val inclinometerAimPrompt = "Наведите перекрестие на линию соприкосновения с землей"
        override val eyeHeightLabel = "Высота глаз (камеры)"
        override val calibrateAfOneMeter = "Калибровка AF на 1.0м"
        override val afCalibrationScale = "Коэффициент масштаба AF"
        override val firstLaunchCalibrationTitle = "💡 Рекомендация перед началом · Калибровка"
        override val firstLaunchCalibrationDesc = "Из-за различий датчиков на разных Android устройствах, рекомендуется откалибровать базовый EV перед съемкой:\n\n1. Сравните замер с внешним экспонометром или iPhone;\n2. Настройте смещение EV в Меню!"
        override val calibrateNowBtn = "Калибровать сейчас"
        override val gotItBtn = "Понятно, начать"
    }

    private object StringsAr : Strings {
        override val appTitle = "مقياس الإضاءة الاحترافي"
        override val filmSelect = "نوع الفيلم"
        override val spotMeter = "قياس نقطي"
        override val matrixMeter = "قياس شامل"
        override val multiSpot = "نقاط متعددة"
        override val lockHold = "تثبيت"
        override val unlockReading = "مثبت"
        override val readingLocked = "تم تثبيت القراءة"
        override val liveMetering = "قياس مباشر"
        override val zoneSystem = "نظام المناطق"
        override val rangefinder = "مقياس المسافة"
        override val torch = "كشاف"
        override val falseColor = "ألوان زائفة"
        override val compensation = "تعويض التعريض"
        override val ndFilter = "مرشح ND"
        override val logShot = "تسجيل اللقطة"
        override val shotLogs = "سجل التعريض"
        override val reciprocityTimer = "مؤقت فشل التبادلية"
        override val framelines = "خطوط الإطار"
        override val settings = "الإعدادات"
        override val menu = "القائمة"
        override val calibrationOffset = "معايرة قيمة التعريض الأساسية"
        override val calibrationDesc = "ضبط قيمة EV لمطابقة أجهزة القياس الفيزيائية Sekonic / Gossen"
        override val reset = "إعادة ضبط"
        override val language = "اللغة"
        override val cameraOptics = "عدسات الكاميرا والبصريات"
        override val lensSwitch = "تبديل العدسة"
        override val ultraWide = "0.6x عريضة جداً"
        override val mainWide = "1.0x عريضة قياسية"
        override val telephoto2x = "2.0x مقربة"
        override val telephoto3x = "3.0x بورتريه مقربة"
        override val telephoto5x = "5.0x فائقة التقريب"
        override val landscapeEquiv = "مكافئ 35 مم أفقي"
        override val portraitEquiv = "مكافئ 35 مم رأسي"
        override val measuredDistance = "المسافة"
        override val distanceMeasuring = "جارٍ قياس المسافة..."
        override val infinityHyperfocal = "∞ (اللانهاية / المسافة المفرطة)"
        override val macroRange = "ماكرو"
        override val tapToMeasure = "المس الشاشة للقياس"
        override val priorityAv = "أولوية فتحة العدسة (Av)"
        override val priorityTv = "أولوية سرعة الغالق (Tv)"
        override val priorityIso = "أولوية الحساسية ISO"
        override val priorityEvLock = "يدوي (قفل EV)"
        override val reciprocityComp = "سرعة الغالق المعوضة"
        override val timerStart = "بدء المؤقت"
        override val timerPause = "إيقاف مؤقت"
        override val timerReset = "إعادة ضبط"
        override val timerCompleted = "اكتمل التعريض"
        override val formatGate = "تنسيق وإطار الفيلم"
        override val gridGuides = "شبكة التكوين"
        override val colorFilters = "مرشحات أبيض وأسود"
        override val digitalCropZoom = "اقتصاص الإطار للبعد البؤري"
        override val clearAll = "مسح الكل"
        override val notePlaceholder = "أضف ملاحظات عن التعريض..."
        override val saveLog = "حفظ"
        override val delete = "حذف"
        override val exposureValue = "قيمة التعريض (EV)"
        override val middleGray = "رمادي محايد 18% (المنطقة V)"

        override val cameraPermissionRequired = "مطلوب إذن الكاميرا للقياس المباشر"
        override val cameraPermissionDesc = "يقرأ بيانات المستشعر لحساب القيمة الدقيقة للإضاءة (EV)"
        override val grantPermission = "منح إذن الكاميرا"
        override val pinSpot = "تثبيت"
        override val apertureLabel = "فتحة العدسة (f)"
        override val shutterLabel = "سرعة الغالق (t)"
        override val isoLabel = "الحساسية ISO"
        override val reciprocityBannerTitle = "تعويض فشل التبادلية مفعل"
        override val reciprocityBannerFormat = "القياس: %s ➔ الفعلي: %s (+%.1f EV)"
        override val openTimer = "المؤقت"
        override val distanceOn = "المسافة: تشغيل"
        override val distanceOff = "المسافة: إيقاف"
        override val menuCalibration = "القائمة · المعايرة / المرشحات"
        override val outOfFovWarning = "%dمم يتجاوز العدسة (%dمم) · انقر للتحويل إلى 0.6x"
        override val switchToUltraWide = "0.6x عريضة جداً"
        override val framelineModeMask = "قناع الإطار"
        override val framelineModeZoom = "تكبير الإطار"
        override val zoneSystemTitle = "نظام المناطق"
        override val alignNaturalZone = "محاذاة الطبيعي Z%s"
        override val matchedNaturalZone = "✓ طبيعي Z%s"
        override val exitSpotMeter = "إنهاء النقطي"
        override val matrixAveragePrompt = "قياس متوسط داخل الإطار · المس للنقطي"
        override val linkSpotDistanceOn = "ربط النقطة: تشغيل"
        override val linkSpotDistanceOff = "ربط النقطة: إيقاف"
        override val zoneOn = "المناطق: تشغيل"
        override val zoneOff = "المناطق: إيقاف"
        override val lowContrastHint = "تباين منخفض · صوّب نحو الحافة"
        override val rangefinderModeTitle = "محرك مقياس المسافة"
        override val inclinometerAimPrompt = "وجّه التقاطع نحو خط ملامسة الهدف للأرض"
        override val eyeHeightLabel = "ارتفاع العين (الكاميرا)"
        override val calibrateAfOneMeter = "معايرة التركيز التلقائي عند 1.0م"
        override val afCalibrationScale = "معامل قياس المسافة AF"
        override val firstLaunchCalibrationTitle = "💡 توصية الاستخدام الأول · معايرة التعريض"
        override val firstLaunchCalibrationDesc = "نظراً لاختلاف المستشعرات بين أجهزة أندرويد، نوصي بمعايرة قيمة EV قبل التصوير:\n\n1. قارن القراءة بجهاز قياس مستقل أو تطبيق iPhone تحت نفس الإضاءة;\n2. اضبط إزاحة EV في القائمة للمطابقة!"
        override val calibrateNowBtn = "معايرة الآن (موصى به)"
        override val gotItBtn = "فهمت، البدء"
    }
}
